fix: use git status so we detect new files properly

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,9 +53,9 @@ jobs:
 
           pushd repo
           cp -r ../go-datatrails-common-api-gen/* .
-          git status
-          if git diff --exit-code; then
-            echo "::warning :: no changes found"
+          if [[ -z "$(git status --short)" ]]; then
+            echo "::error :: no changes found"
+            exit 1
           fi
 
       # We don't, as a matter of policy, lint generated code. Any deep tests on
@@ -66,7 +66,7 @@ jobs:
         with:
           go-version: '1.21.x'
 
-      - name: Build the sources
+      - name: Unit tests
         working-directory: repo
         run: |
           go build ./...
@@ -75,12 +75,13 @@ jobs:
       - name: Commit the updates
         working-directory: repo
         run: |
-          if git diff --exit-code; then
-            echo "::warning :: no changes found"
-            exit 0
+          if [[ -z "$(git status --short)" ]]; then
+            echo "::error :: no changes found"
+            exit 1
           fi
           git config --global user.name 'CI Workflow'
           git config --global user.email $COMMIT_EMAIL
+          git add .
           git commit -am "feat: updated to go-datatrails-common-api@$TAG"
           git push
 
